repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: detect-private-key
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black-jupyter
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.285'
    hooks:
      - id: ruff
        files: ^(FlipKartCXDemo\.ipynb|setup\.py)
        args: ["--fix"]
# https://pre-commit.ci/
ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: false
    autoupdate_branch: 'main'
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: monthly
    submodules: false
